"""E2E tests for the license server and exported package heartbeat."""
from __future__ import annotations

import ast
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

import httpx
import pytest

sys.path.insert(0, str(Path(__file__).parent.parent.parent / "license-server"))

from db import LicenseDB
from main import app, get_db


pytestmark = [pytest.mark.e2e]

ADMIN_HEADERS = {"X-Admin-Token": "dev-token"}


# ---------------------------------------------------------------------------
# Fixtures (local)
# ---------------------------------------------------------------------------

@pytest.fixture
def mem_db() -> LicenseDB:
    return LicenseDB(db_path=":memory:")


@pytest.fixture
async def license_client(mem_db: LicenseDB):
    app.dependency_overrides[get_db] = lambda: mem_db
    transport = httpx.ASGITransport(app=app)
    async with httpx.AsyncClient(transport=transport, base_url="http://test") as c:
        yield c, mem_db
    app.dependency_overrides.clear()


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _paid_until(days: int) -> str:
    dt = datetime.now(timezone.utc) + timedelta(days=days)
    return dt.date().isoformat()


async def _create_client_e2e(c, name="E2E Corp", pkg="basic", days=30) -> dict:
    res = await c.post(
        "/clients",
        json={"name": name, "package_type": pkg, "paid_until": _paid_until(days)},
        headers=ADMIN_HEADERS,
    )
    assert res.status_code == 200, f"Error creando cliente: {res.text}"
    return res.json()


async def _heartbeat_e2e(c, client_id: str, license_key: str) -> httpx.Response:
    return await c.post(
        "/heartbeat",
        json={
            "client_id": client_id,
            "license_key": license_key,
            "package_type": "basic",
            "timestamp": datetime.now(timezone.utc).isoformat(),
        },
    )


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

async def test_license_full_lifecycle(license_client):
    """Full lifecycle: create → heartbeat(active) → block → heartbeat(inactive) → unblock → heartbeat(active)."""
    c, db = license_client

    # 1. Create client
    data = await _create_client_e2e(c)
    cid, key = data["id"], data["license_key"]

    # 2. Heartbeat while active
    hb1 = await _heartbeat_e2e(c, cid, key)
    assert hb1.status_code == 200
    assert hb1.json()["active"] is True

    # 3. Block client
    block_res = await c.post(f"/clients/{cid}/block", headers=ADMIN_HEADERS)
    assert block_res.status_code == 200

    # 4. Heartbeat while blocked
    hb2 = await _heartbeat_e2e(c, cid, key)
    assert hb2.status_code == 200
    assert hb2.json()["active"] is False

    # 5. Unblock client
    unblock_res = await c.post(f"/clients/{cid}/unblock", headers=ADMIN_HEADERS)
    assert unblock_res.status_code == 200

    # 6. Heartbeat after unblock
    hb3 = await _heartbeat_e2e(c, cid, key)
    assert hb3.status_code == 200
    assert hb3.json()["active"] is True


def test_exported_heartbeat_valid_syntax_and_content(tmp_path):
    """heartbeat.py generated by PackageBuilder must parse without errors and contain key symbols."""
    from export.builder import PackageBuilder

    builder = PackageBuilder(
        client_id="e2e-hb-test",
        client_name="E2E Heartbeat Test",
        package_type="basic",
        license_key="E2E-HB-001",
        license_server_url="http://localhost:8080",
        groups=["content_pipeline"],
        output_base=tmp_path,
    )
    package_path = builder.build()

    # Find heartbeat.py inside the generated package
    hb_files = list(package_path.rglob("heartbeat.py"))
    assert len(hb_files) >= 1, "heartbeat.py no encontrado en el paquete exportado"

    hb_file = hb_files[0]
    source = hb_file.read_text(encoding="utf-8", errors="replace")

    # Syntax check
    try:
        ast.parse(source)
    except SyntaxError as e:
        pytest.fail(f"heartbeat.py tiene error de sintaxis: {e}")

    # Content checks — must contain essential symbols
    assert "_send_heartbeat" in source, "heartbeat.py no define _send_heartbeat"
    assert "_load_config" in source, "heartbeat.py no define _load_config"
    assert "license_key" in source, "heartbeat.py no referencia license_key"
